version: '2'

services:
    fhem:
        restart: always
        ports:
            - "8083:8083"
            - "7072:7072"
        image: fhem/fhem:latest
        volumes:
            - ./fhem/core/:/opt/fhem/
            - /dev/serial/by-id:/dev/serial/by-id
        build: fhem
        privileged: true
        devices:
            - "dev/ttyUSB0:/dev/ttyUSB0"
            - "dev/ttyUSB1:/dev/ttyUSB1"    
        networks:
            - fhem-network
        environment:
            FHEM_UID: 1000
            FHEM_GID: 1000
            TIMEOUT: 10
            RESTART: 1
            TELNETPORT: 7072
            TZ: Europe/Berlin
        depends_on:
            - "mysql"
            - "mqtt"

    mysql:
        restart: always
        expose:
            - "3306"
            - "33060"
        ports:
            - "3306:3306"
            - "33060:33060"
        image: mysql/mysql-server:5.7
        volumes:
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/fhem-init.sql
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        networks:
            - fhem-network

    mqtt:
        restart: always
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"
        image: toke/mosquitto
        networks:
            - fhem-network
        volumes:
            - ./mqtt/config/:/mqtt/config/
            - ./mqtt/log/:/mqtt/log/
            - ./mqtt/data/:/mqtt/data/

    nodered:
        restart: always
        expose:
            - "1880"
        ports:
            - "1880:1880"
        image: nodered/node-red-docker:0.18.4
        user: "1000:1000"
        volumes:
            - ./nodered/data/:/data/
        networks:
            - fhem-network
        depends_on:
            - "mqtt"
            
    homebridge:
        image: oznu/homebridge:latest
        restart: always
        ports:
            - "8282:8282"
            - "5353:5353"
            - "51830:51830"
        network_mode: host
        environment:
            - PGID=1000
            - PUID=1000
        volumes:
            - ./homebridge:/homebridge
            
    alexa-fhem:
        image: fhem/alexa-fhem:latest
        restart: always
        networks:
            - fhem-network
        ports:
            - "3000:3000"
        volumes:
            - "./alexa-fhem/:/alexa-fhem/"
        environment:
            ALEXAFHEM_UID: 6062
            ALEXAFHEM_GID: 6062
            TZ: Europe/Berlin
            
    diyHue:
        image: diyhue/core:latest
        restart: always
        network_mode: host
        volumes:
            - ./mnt/hue-emulator/export/:/opt/hue-emulator/export/
                
networks:
    fhem-network:
        driver: bridge